# Generated by Django 5.0.3 on 2024-04-01 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HIT",
            fields=[
                ("id", models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name="HIT ID")),
                ("enabled", models.BooleanField(default=True, verbose_name="enabled")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at")),
                ("topic", models.CharField(max_length=1024, verbose_name="topic")),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("sandbox", "Sandbox"),
                            ("prod", "Production"),
                            ("local", "Local only (not on Mechanical Turk)"),
                        ],
                        default="sandbox",
                        max_length=7,
                        verbose_name="location",
                    ),
                ),
            ],
            options={
                "verbose_name": "HIT",
                "ordering": ("-created_at", "id"),
                "get_latest_by": "created_at",
            },
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                ("id", models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name="worker ID")),
                ("name", models.CharField(blank=True, max_length=40, verbose_name="name")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                        default="male",
                        max_length=6,
                        verbose_name="gender",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name="assignment ID"),
                ),
                (
                    "stage",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Handshake completed"), (1, "Verified"), (2, "HIT Complete")],
                        default=0,
                        verbose_name="stage",
                    ),
                ),
                ("hit", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.hit")),
                ("worker", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.worker")),
            ],
        ),
    ]
