# Generated by Django 5.0.3 on 2024-04-02 21:46

import datetime
import django.core.validators
import django.db.models.deletion
import django_countries.fields
import django_jsonform.models.fields
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amazon_id", models.CharField(max_length=255, null=True, unique=True, verbose_name="Amazon ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at")),
                ("name", models.CharField(blank=True, max_length=40, verbose_name="name")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                        default="male",
                        max_length=6,
                        verbose_name="gender",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HIT",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amazon_id", models.CharField(max_length=255, null=True, unique=True, verbose_name="Amazon ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at")),
                ("name", models.CharField(help_text="Not sent to MTurk.", max_length=100, verbose_name="code name")),
                ("enabled", models.BooleanField(default=True)),
                ("topic", models.CharField(max_length=1024, verbose_name="topic")),
                (
                    "status",
                    models.CharField(
                        choices=[("sandbox", "Sandbox"), ("prod", "Production"), ("local", "Local (not submitted)")],
                        default="local",
                        max_length=7,
                        verbose_name="status",
                    ),
                ),
                ("title", models.CharField(max_length=1024, verbose_name="title (on MTurk)")),
                ("description", models.TextField(verbose_name="description (on MTurk)")),
                ("keywords", models.TextField(verbose_name="keywords (on MTurk)")),
                ("unique_request_token", models.UUIDField(default=uuid.uuid4)),
                ("submitted_at", models.DateTimeField(default=None, null=True)),
                (
                    "duration",
                    models.DurationField(
                        validators=[
                            django.core.validators.MinValueValidator(datetime.timedelta(seconds=30)),
                            django.core.validators.MaxValueValidator(datetime.timedelta(days=365)),
                        ],
                        verbose_name="duration of HIT",
                    ),
                ),
                ("approval_code", models.UUIDField(default=uuid.uuid4)),
                (
                    "approval_delay",
                    models.DurationField(
                        default=datetime.timedelta(days=3),
                        help_text="After this time, an approved assignment will be automatically approved.",
                        validators=[
                            django.core.validators.MinValueValidator(datetime.timedelta(seconds=30)),
                            django.core.validators.MaxValueValidator(datetime.timedelta(days=365)),
                        ],
                    ),
                ),
                (
                    "assignment_duration",
                    models.DurationField(
                        validators=[
                            django.core.validators.MinValueValidator(datetime.timedelta(seconds=30)),
                            django.core.validators.MaxValueValidator(datetime.timedelta(days=365)),
                        ],
                        verbose_name="duration of individual assignment",
                    ),
                ),
                (
                    "assignment_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(500),
                        ],
                        verbose_name="maximum number of assignments",
                    ),
                ),
                (
                    "assignment_reward",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("99.99")),
                        ],
                        verbose_name="individual reward for assignment",
                    ),
                ),
                (
                    "qualification_masters",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Worker qualification. When enabled only workers with the 'Masters' qualification can do"
                            " this HIT."
                        ),
                        verbose_name="masters qualification",
                    ),
                ),
                (
                    "qualification_num_previously_approved",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Worker qualification. Set to 0 to disable.",
                        verbose_name="assignments previously approved",
                    ),
                ),
                (
                    "qualification_approval_rate",
                    models.PositiveIntegerField(
                        default=0,
                        help_text=(
                            "Worker qualification. Worker's assignment approval rate qualification. Set to 0 to"
                            " disable."
                        ),
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="approval rate (percentage)",
                    ),
                ),
                (
                    "qualification_countries",
                    django_countries.fields.CountryField(
                        blank=True,
                        default=(
                            "AG",
                            "AU",
                            "BS",
                            "BB",
                            "BZ",
                            "CA",
                            "DM",
                            "GD",
                            "GY",
                            "IE",
                            "JM",
                            "MT",
                            "NZ",
                            "KN",
                            "LC",
                            "VC",
                            "ZA",
                            "TT",
                            "GB",
                            "US",
                        ),
                        help_text="Worker qualification. Limit workers to these countries. Leave blank to disable.",
                        max_length=746,
                        multiple=True,
                        verbose_name="countries",
                    ),
                ),
                (
                    "qualification_adult",
                    models.BooleanField(
                        default=False,
                        help_text="Worker qualification. Enable to require workers over 18",
                        verbose_name="adult qualification",
                    ),
                ),
                (
                    "publish_api_exception",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text=(
                            "The last contains of the last error (if any) that occurred while publishing this HIT to"
                            " MTurk"
                        ),
                        verbose_name="error details",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "HIT",
                "ordering": ("-created_at", "id"),
                "get_latest_by": "created_at",
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amazon_id", models.CharField(max_length=255, null=True, unique=True, verbose_name="Amazon ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at")),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("initial", "Handshake completed"),
                            ("verified", "Verified"),
                            ("call-initiated", "Call initiated"),
                            ("call-connected", "Call connected"),
                            ("left-voicemail", "Left voicemail"),
                            ("call-completed", "Call completed"),
                            ("done", "HIT Complete"),
                        ],
                        default="initial",
                        max_length=14,
                        verbose_name="stage",
                    ),
                ),
                (
                    "call_started_at",
                    models.DateTimeField(blank=True, default=None, null=True, verbose_name="call started at"),
                ),
                ("words_to_pronounce", django_jsonform.models.fields.JSONField()),
                ("hit", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.hit")),
                ("worker", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.worker")),
            ],
            options={
                "ordering": ("-created_at", "id"),
                "get_latest_by": "created_at",
            },
        ),
    ]
