# Generated by Django 5.0.4 on 2024-04-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_assignment_changes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="worker",
            options={"permissions": (("block_worker", "Can block workers"),)},
        ),
        migrations.AddField(
            model_name="worker",
            name="blocked",
            field=models.BooleanField(default=False, verbose_name="blocked"),
        ),
    ]
