# Generated by Django 5.0.4 on 2024-04-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_block_workers"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerPageLoad",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at")),
                (
                    "worker_amazon_id",
                    models.CharField(
                        db_index=True,
                        help_text="Worker identifier as used by the Amazon MTurk API.",
                        max_length=255,
                        verbose_name="Worker Amazon ID",
                    ),
                ),
                (
                    "assignment_amazon_id",
                    models.CharField(
                        blank=True,
                        help_text="Assignment identifier as used by the Amazon MTurk API.",
                        max_length=255,
                        null=True,
                        verbose_name="Assignment Amazon ID",
                    ),
                ),
                (
                    "hit_amazon_id",
                    models.CharField(
                        blank=True,
                        help_text="HIT identifier as used by the Amazon MTurk API.",
                        max_length=255,
                        null=True,
                        verbose_name="HIT Amazon ID",
                    ),
                ),
                (
                    "had_amp_encoded",
                    models.BooleanField(
                        default=False,
                        help_text="Request had &amp; encoded. This appears to be a marker of spam.",
                        verbose_name="Had &amp; encoded",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="worker",
            options={
                "get_latest_by": "created_at",
                "ordering": ("-created_at", "id"),
                "permissions": (("block_worker", "Can block workers"),),
            },
        ),
    ]
