# Generated by Django 5.0.4 on 2024-04-09 20:53

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_worker_page_loads"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="user_agent",
            field=models.CharField(blank=True, max_length=1024, verbose_name="user agent"),
        ),
        migrations.AlterField(
            model_name="hit",
            name="leave_voicemail_after_duration",
            field=models.DurationField(
                default=datetime.timedelta(seconds=600),
                help_text=(
                    'After this amount of time of being on "hold" the worker can submit the assignment with a'
                    " voicemail."
                ),
                validators=[
                    django.core.validators.MinValueValidator(datetime.timedelta(seconds=30)),
                    django.core.validators.MaxValueValidator(datetime.timedelta(seconds=3600)),
                ],
                verbose_name="duration to leave a voicemail after",
            ),
        ),
    ]
