# Generated by Django 5.1.2 on 2024-10-13 23:04

import datetime
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_good_workers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Caller",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at")),
                ("name", models.CharField(blank=True, help_text="Optional name for caller", max_length=100)),
                (
                    "wants_calls",
                    models.BooleanField(
                        default=False, help_text="Caller wants solicited calls", verbose_name="wants to be called"
                    ),
                ),
                ("number", phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ("location", models.CharField(default="Unknown", max_length=1024, verbose_name="location")),
            ],
            options={
                "verbose_name": "phone caller",
                "ordering": ("-created_at", "id"),
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="assignment",
            options={
                "get_latest_by": "created_at",
                "ordering": ("-created_at", "id"),
                "verbose_name": "MTurk assignment",
            },
        ),
        migrations.AlterModelOptions(
            name="hit",
            options={
                "get_latest_by": "created_at",
                "ordering": ("-created_at", "id"),
                "permissions": (
                    ("preview_hit", "Can preview HIT (frontend)"),
                    ("publish_sandbox_hit", "Can publish HIT to MTurk (Sandbox)"),
                    ("publish_production_hit", "Can publish HIT to MTurk (Production)"),
                ),
                "verbose_name": "MTurk HIT",
            },
        ),
        migrations.AlterModelOptions(
            name="worker",
            options={
                "get_latest_by": "created_at",
                "ordering": ("-created_at", "id"),
                "permissions": (("block_worker", "Can block workers"),),
                "verbose_name": "MTurk worker",
            },
        ),
        migrations.AlterModelOptions(
            name="workerpageload",
            options={
                "get_latest_by": "created_at",
                "ordering": ("-created_at", "id"),
                "verbose_name": "MTurk worker page load",
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this topic currently active.", verbose_name="active"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Topic name (for internal cataloguing).", max_length=100, verbose_name="name"
                    ),
                ),
                (
                    "recording",
                    models.FileField(
                        help_text=(
                            "Add your recorded topic here. The prompt for it is: \"Here's what we're currently talking"
                            ' about:" or "The current topic is:"'
                        ),
                        upload_to="topics/",
                        verbose_name="recording",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "phone call topic",
                "ordering": ("-created_at", "id"),
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Voicemail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at")),
                ("duration", models.DurationField(default=datetime.timedelta(0), verbose_name="duration")),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "caller",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.caller"
                    ),
                ),
            ],
            options={
                "verbose_name": "phone voicemail",
                "ordering": ("-created_at", "id"),
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
    ]
