services:
  backend:
    restart: always
    image: ghcr.io/dtcooper/radio-calls-backend:latest
    build:
      context: backend
      args:
        DEBUG: "${DEBUG:-0}"
    volumes:
      - ./backend/static:/static
      - ./backend/media:/media
    env_file: .env
    mem_limit: 2048m
    depends_on:
      - db

  frontend-build:
    restart: on-failure
    image: node:21.7
    environment:
      TZ: "${TZ}"
    command: sh -c "npm install && npm run build"
    working_dir: /app/frontend
    volumes:
      - .:/app
    profiles:
      - build

  nginx:
    restart: always
    image: jonasal/nginx-certbot:5.2-alpine
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/templates/site.conf.template
      - ./frontend:/frontend
      - ./backend/static:/static
      - ./backend/media:/media
      - nginx_secrets:/etc/letsencrypt
    environment:
      TZ: "${TZ}"
      DOMAIN_NAME: "${DOMAIN_NAME}"
      CERTBOT_EMAIL: "${CERTBOT_EMAIL}"
      __NGINX_BACKEND_STATIC_CONF: |
        location /static/ {
                alias /static/;
            }
        location /media/ {
                alias /media/;
            }
      __NGINX_FRONTEND_CONF: |
        # Frontend static assets (immutable)
            location /hit/_app/immutable {
                alias /frontend/build/_app/immutable;
                expires max;
                add_header Cache-Control "public, immutable";
                access_log off;
            }

            # Frontend static assets (Internal, as it's X-Accel-Redirect proxied through nginx)
            location /__hit_passthrough__/hit {
                internal;
                expires 0;
                alias /frontend/build;
            }
    ports:
      - 80:80
      - 443:443

  db:
    restart: always
    image: pgautoupgrade/pgautoupgrade:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "${TZ}"

volumes:
  nginx_secrets:
  postgres_data:
