services:
  backend:
    restart: "no"
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
  frontend:
    restart: "no"
    ports:
      - 5173:5173
  nginx:
    restart: "no"
    profiles:
      - prod
  db:
    restart: "no"
