services:
  backend:
    restart: always
    image: ghcr.io/dtcooper/radio-calls-backend:latest
    build:
      context: backend
      args:
        DEV_MODE: "${DEV_MODE:-0}"
    volumes:
      - ./backend/static:/static
    env_file: .env
    mem_limit: 2048m
    depends_on:
      - db

  frontend:
    restart: on-failure
    image: node:21.7-alpine
    env_file: .env
    command: sh -c "npm install && npm run build"
    working_dir: /app
    volumes:
      - ./frontend:/app

  nginx:
    restart: always
    image: jonasal/nginx-certbot:5.0-alpine
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/templates/site.conf.template
      - ./frontend:/frontend
      - ./backend/static:/backend-static
      - nginx_secrets:/etc/letsencrypt
    environment:
      DOMAIN_NAME: "${DOMAIN_NAME}"
      CERTBOT_EMAIL: "${CERTBOT_EMAIL}"
      __NGINX_BACKEND_STATIC_CONF: |
        location /backend-static/ {
                alias /backend-static/;
            }
      __NGINX_FRONTEND_CONF: |
        # Frontend static assets (immutable)
            location /hit/_app/immutable/ {
                root /frontend/build;
                expires max;
                add_header Cache-Control "public, immutable";
                access_log off;
            }

            # Frontend static assets
            location /hit {
                alias /frontend/build;
            }
    ports:
      - 80:80
      - 443:443

  db:
    restart: always
    image: postgres:16.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  nginx_secrets:
  postgres_data:
