services:
  backend:
    restart: "no"
    volumes:
      - ./backend:/app
    ports:
      - 127.0.0.1:8000:8000
  frontend:
    restart: "no"
    profiles:
      - prod-only
  nginx:
    restart: "no"
  db:
    restart: "no"
    ports:
      - 127.0.0.1:5432:5432
