services:
  backend:
    restart: "no"
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
  frontend:
    restart: "no"
    ports:
      - 5173:5173
  nginx:
    restart: "no"
  db:
    restart: "no"
    ports:
      - 127.0.0.1:5432:5432
