[tool.poetry]
name = "calls"
version = "0.0.1"
description = "Radio Calls server"
authors = ["David Cooper <david@dtcooper.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0.3"
django-environ = "^0.11.2"
django-ninja = "^1.1.0"
gunicorn = "^21.2.0"
psycopg = "^3.1.18"
twilio = "^9.0.2"
wait-for-it = "^2.2.2"

[tool.poetry.group.dev.dependencies]
black = "^24.3.0"
django-extensions = "^3.2.3"
flake8 = "^7.0.0"
ipython = "^8.22.2"
isort = "^5.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
