name: Build & deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: build-deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build container
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set variables
        shell: bash
        run: |
          echo "SHA_SHORT=$(git rev-parse --short=8 HEAD)" >> "$GITHUB_ENV"
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: dtcooper
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          pull: true
          platforms: linux/amd64
          context: ./backend/
          tags: |
            ghcr.io/dtcooper/radio-calls-backend:latest
            ghcr.io/dtcooper/radio-calls-backend:${{ env.SHA_SHORT }}
      # -
      #   name: Deploy
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     port: ${{ secrets.SSH_PORT }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.SSH_KEY }}
      #     # Generate via:
      #     #   $ ssh <host> ssh-keygen -l -f /etc/ssh/ssh_host_ecdsa_key.pub | cut -d ' ' -f2
      #     fingerprint: ${{ secrets.SSH_FINGERPRINT }}
      #     script_stop: true
      #     # Steps:
      #     #  1. git pull, fast-forward only
      #     #  2. pull containers
      #     #  3. bring down all containers
      #     #  4. bring up containers in detatched mode
      #     #  5. Set redis keys describing deployment (date, URL of workflow)
      #     #  6. remove all extraneous docker container data (prune)
      #     script: |
      #       cd radio-calls
      #       make build-pull
